"""
FastAPI backend (CDC continuation section 25/14).

Serves the forecast dataset built by scripts/04 or script 10. Every forecast response
carries data_source/forecast_status fields so a client can never mistake demo
output for validated real forecasts.

Run:
    uvicorn src.api.main:app --reload --port 8000
Docs:
    http://localhost:8000/docs (auto-generated by FastAPI)
"""
from __future__ import annotations

import io
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd
from fastapi import FastAPI, HTTPException, Query
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

from src.aggregation.hierarchical import reconcile_all_levels, check_consistency
from src.ingestion.data_mode import get_data_mode
from src.monitoring.drift import weather_drift_report, production_drift_report, anomaly_flags
from src.forecasting.backtesting import evaluate
from src.forecasting import national_hybrid as NH
from src.forecasting import real_service as RS

app = FastAPI(
    title="PESTGM 7.0 Track 1 - PV Forecast API",
    description="National PV forecasting platform for Tunisia. "
                 "DATA_MODE currently determines whether responses are demo-labelled.",
    version="0.4.0",
)

DATA_PATH = Path("data/processed/training_dataset_15min_real_reference_sample.csv")
TARGET_COL = "pv_production_mw_reference"
MODEL_VERSION = "pestgm-reference-lightgbm-0.3"

if not DATA_PATH.exists():
    DATA_PATH = Path("data/processed/training_dataset_15min_sample.csv")
    TARGET_COL = "pv_production_mw_proxy"
    MODEL_VERSION = "demo-physics-lightgbm-0.2"

_CACHE: dict = {}


def _load() -> pd.DataFrame:
    if not DATA_PATH.exists():
        raise HTTPException(status_code=503, detail=f"{DATA_PATH} not built yet - run scripts/04 or 10.")
    if "df" not in _CACHE:
        d = pd.read_csv(DATA_PATH, parse_dates=["timestamp"])
        if "capacity_mw" not in d.columns and "installed_capacity_mw" in d.columns:
            d["capacity_mw"] = d["installed_capacity_mw"]
        d[NH.FCOL] = NH.hybrid_forecast_mw(d)
        _CACHE["df"] = d
    return _CACHE["df"]


def _levels(df: pd.DataFrame) -> dict:
    """Bottom-up levels carrying BOTH the model forecast and the reference/target column."""
    f = reconcile_all_levels(df, NH.FCOL)
    r = reconcile_all_levels(df, TARGET_COL)
    keys = {"district": ["timestamp", "district_id"], "governorate": ["timestamp", "governorate"], "national": ["timestamp"]}
    return {k: f[k].merge(r[k][keys[k] + [TARGET_COL]], on=keys[k]) for k in f}


class ForecastPoint(BaseModel):
    forecast_issue_time: str
    target_timestamp: str
    horizon: str
    spatial_level: str
    entity: str
    forecast_mw: float
    p10_mw: float | None = None
    p50_mw: float | None = None
    p90_mw: float | None = None
    reference_mw: float | None = None
    forecast_method: str = "calibrated-physics hybrid (ENSTAB-calibrated)"
    model_version: str
    data_source: str
    forecast_status: str
    generation_time: str


class ForecastRequest(BaseModel):
    spatial_level: str  # district | governorate | national
    entity: str
    horizon: str = "intraday_15min"


def _data_source_label(df: pd.DataFrame) -> str:
    if df is not None and "_src" in df.attrs:
        return df.attrs["_src"]
    col = "production_source" if TARGET_COL == "pv_production_mw_reference" else "pv_production_source"
    return df[col].iloc[0] if col in df.columns and len(df) else "UNKNOWN"


def _forecast_status_label(df: pd.DataFrame) -> str:
    label = _data_source_label(df)
    return label if label != "UNKNOWN" else "SIMULATED"


@app.get("/health")
def health():
    return {"status": "ok", "data_mode": get_data_mode().value, "time": datetime.now(timezone.utc).isoformat()}


@app.get("/districts")
def districts():
    df = _load()
    out = df.drop_duplicates("district_id")[["district_id", "district", "governorate", "latitude", "longitude"]]
    return out.to_dict(orient="records")


@app.get("/capacity")
def capacity(district_id: str | None = None):
    df = _load()
    if district_id:
        df = df[df["district_id"] == district_id]
        if df.empty:
            raise HTTPException(404, f"Unknown district_id {district_id}")
    latest = df.sort_values("timestamp").groupby("district_id").tail(1)
    
    cap_col = "capacity_mw" if "capacity_mw" in df.columns else "installed_capacity_mw"
    src_col = "capacity_source" if "capacity_source" in df.columns else "fleet_snapshot_source"
    
    res = latest[["district_id", "district", "governorate", "timestamp", cap_col, src_col]].copy()
    res = res.rename(columns={cap_col: "capacity_mw", src_col: "capacity_source"})
    return res.to_dict(orient="records")


def _points_from_series(sub: pd.DataFrame, level: str, entity: str, now: str) -> list[dict]:
    sub.attrs["_src"] = _data_source_label(_load())
    return [
        ForecastPoint(
            forecast_issue_time=now, target_timestamp=row["timestamp"].isoformat() if hasattr(row["timestamp"], "isoformat") else str(row["timestamp"]),
            horizon="intraday_15min", spatial_level=level, entity=entity,
            forecast_mw=float(row[NH.FCOL]), reference_mw=float(row[TARGET_COL]),
            model_version=MODEL_VERSION, data_source=_data_source_label(sub),
            forecast_status=_forecast_status_label(sub), generation_time=now,
        ).model_dump()
        for _, row in sub.iterrows()
    ]


@app.get("/forecast/district/{district_id}")
def forecast_district(district_id: str):
    df = _load()
    g = df[df["district_id"] == district_id]
    if g.empty:
        raise HTTPException(404, f"Unknown district_id {district_id}")
    now = datetime.now(timezone.utc).isoformat()
    return _points_from_series(_levels(g)["district"].sort_values("timestamp"), "district", district_id, now)


@app.get("/forecast/governorate/{governorate}")
def forecast_governorate(governorate: str):
    df = _load()
    g = df[df["governorate"] == governorate]
    if g.empty:
        raise HTTPException(404, f"Unknown governorate {governorate}")
    levels = _levels(g)
    now = datetime.now(timezone.utc).isoformat()
    return _points_from_series(levels["governorate"], "governorate", governorate, now)


@app.get("/forecast/national")
def forecast_national():
    df = _load()
    levels = _levels(df)
    now = datetime.now(timezone.utc).isoformat()
    return _points_from_series(levels["national"], "national", "TUNISIA", now)


@app.post("/forecast")
def post_forecast(req: ForecastRequest):
    """Generic forecast endpoint: dispatches to the district/governorate/national
    getters above based on the request body (CDC-required POST /forecast)."""
    if req.spatial_level == "district":
        return forecast_district(req.entity)
    if req.spatial_level == "governorate":
        return forecast_governorate(req.entity)
    if req.spatial_level == "national":
        return forecast_national()
    raise HTTPException(400, "spatial_level must be one of district|governorate|national")


@app.get("/uncertainty")
def uncertainty(district_id: str, horizon: str = "J+1"):
    """P10/P50/P90 for a district: model forecast with an interval TRANSFERRED from the
    ENSTAB conformal-calibrated ratios (see src/forecasting/national_hybrid.py)."""
    df = _load()
    g = df[df["district_id"] == district_id].sort_values("timestamp")
    if g.empty:
        raise HTTPException(404, f"Unknown district_id {district_id}")
    iv = NH.add_interval(g[NH.FCOL], g["capacity_mw"], horizon)
    out = pd.concat([g[["timestamp"]], iv], axis=1)
    out["pv_production_mw_forecast"] = out["p50_mw"]
    return out.to_dict(orient="records")


@app.get("/errors")
def errors(district_id: str):
    """Forecast-vs-actual error using persistence as the stand-in 'forecast'
    (DEMO_ONLY - a genuine ML-forecast-vs-actual log requires the scripts/05-07
    pipeline artifacts; this endpoint demonstrates the schema and computation)."""
    df = _load()
    g = df[df["district_id"] == district_id].sort_values("timestamp").copy()
    if g.empty:
        raise HTTPException(404, f"Unknown district_id {district_id}")
        
    cap_col = "capacity_mw" if "capacity_mw" in g.columns else "installed_capacity_mw"
        
    g["persistence_forecast_mw"] = g[TARGET_COL].shift(1)
    g = g.dropna(subset=["persistence_forecast_mw"])
    m = evaluate(g[TARGET_COL], g["persistence_forecast_mw"], g[cap_col])
    return {"district_id": district_id, "baseline": "persistence", "metrics": m}


@app.get("/anomalies")
def anomalies(district_id: str | None = None):
    df = _load()
    if district_id:
        df = df[df["district_id"] == district_id]
        if df.empty:
            raise HTTPException(404, f"Unknown district_id {district_id}")
    flags = anomaly_flags(df, production_col=TARGET_COL)
    flagged = flags[flags["physical_anomaly_flag"]]
    return {
        "n_checked": len(flags),
        "n_flagged": len(flagged),
        "pct_flagged": round(100 * len(flagged) / max(len(flags), 1), 3),
        "sample_flagged_rows": flagged.head(20).to_dict(orient="records"),
    }


@app.get("/drift/weather")
def drift_weather():
    df = _load()
    ref_end = df["timestamp"].quantile(0.5)
    report = weather_drift_report(df, ref_end)
    return report.to_dict(orient="records")


@app.get("/drift/production")
def drift_production():
    df = _load()
    ref_end = df["timestamp"].quantile(0.5)
    return production_drift_report(df, TARGET_COL, ref_end)


@app.get("/export")
def export(spatial_level: str = Query("national"), entity: str = Query("TUNISIA"), fmt: str = Query("json")):
    """Grid/load-forecasting integration export (CDC Phase 15). fmt=json|csv."""
    if spatial_level == "district":
        data = forecast_district(entity)
    elif spatial_level == "governorate":
        data = forecast_governorate(entity)
    else:
        data = forecast_national()
    if fmt == "csv":
        buf = io.StringIO()
        pd.DataFrame(data).to_csv(buf, index=False)
        buf.seek(0)
        return StreamingResponse(buf, media_type="text/csv",
                                  headers={"Content-Disposition": f"attachment; filename={spatial_level}_{entity}.csv"})
    return data


# ------------------------------------------------------------------ REAL (measured) data
@app.get("/real/benchmark")
def real_benchmark():
    """Measured-performance benchmark on ENSTAB (scripts/12_real_benchmark.py)."""
    base = Path("data/validation")
    try:
        m = pd.read_csv(base / "real_benchmark_metrics.csv")
        c = pd.read_csv(base / "real_benchmark_coverage.csv")
    except FileNotFoundError:
        raise HTTPException(503, "Run scripts/12_real_benchmark.py first.")
    return {"data_source": "MEASURED_REAL_ENSTAB", "metrics": m.round(3).to_dict("records"),
            "coverage": c.round(2).to_dict("records")}


@app.get("/real/forecast")
def real_forecast(horizon: str = "J+1", start: str = "2024-04-01", days: int = 3):
    """Stored out-of-sample test forecasts vs measured production (test period Dec 2023 - May 2024)."""
    try:
        f = pd.read_csv("data/validation/real_test_forecasts.csv.gz", parse_dates=["timestamp"])
    except FileNotFoundError:
        raise HTTPException(503, "Run scripts/12_real_benchmark.py first.")
    f = f[(f.horizon == horizon) & (f.timestamp >= start) & (f.timestamp < pd.Timestamp(start) + pd.Timedelta(days=days))]
    if f.empty:
        raise HTTPException(404, "No rows for that horizon/period (test period is 2023-12-01..2024-05-31).")
    f = f.assign(timestamp=f.timestamp.astype(str), data_source="MEASURED_REAL_ENSTAB")
    return f.drop(columns=["issue_time"]).to_dict("records")


@app.get("/real/predict")
def real_predict(issue_time: str = "2024-04-10T10:00", horizon: str = "J+1"):
    """LIVE model inference (replay): features built only from data <= issue_time."""
    try:
        return RS.predict(issue_time, horizon)
    except ValueError as e:
        raise HTTPException(400, str(e))
    except LookupError as e:
        raise HTTPException(404, str(e))


@app.get("/model/status")
def model_status():
    if TARGET_COL == "pv_production_mw_reference":
        return {
            "model_version": MODEL_VERSION,
            "data_mode": get_data_mode().value,
            "trained_on": "PHYSICAL_REFERENCE / SYNTHETIC_DEMO",
            "note": "Real measured validation: see /real/benchmark (ENSTAB).",
        }
    return {
        "model_version": MODEL_VERSION,
        "data_mode": get_data_mode().value,
        "trained_on": "DEMO_PROXY_PHYSICS_SIMULATION (see docs/DATA_READINESS_REPORT.md)",
        "note": "National target is simulated. Real measured validation on ENSTAB: /real/benchmark, /real/predict.",
        "forecast_method": "physics calibrated on measured ENSTAB data (configs/calibration_enstab.json)",
    }
